services:
  application:
    image: ts-bones-app
    build: ./
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: .
        target: /app
      # - node_modules:/app/node_modules

volumes:
  node_modules:
