# syntax=docker/dockerfile:1
   
FROM node:slim as builder
WORKDIR /app
COPY ./package.json ./yarn.lock /app
RUN yarn install --frozen-lockfile
COPY . . 
RUN yarn build

FROM node:slim

ENV NODE_ENV production

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile
COPY --from=builder /app/dist ./dist
EXPOSE 8080
CMD ["node", "dist/index.js"]
